replicaCount: 2
image:
  repository: ghcr.io/gulsam00/frontend-practice
  tag: ca843471503d2e77f2ca91ea4295dba185714424
  pullPolicy: IfNotPresent
config:
  apiBaseUrl: "http://backend-mock-service/api"
