name: build-and-push
on:
  push:
    branches: [main]
    paths:
      - "02/frontend-practice/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./02/frontend-practice
          push: true
          tags: ghcr.io/gulsam00/frontend-practice:${{ github.sha }}
